server:
  port: 8002
spring:
  application:
    name: shopp-product
  datasource:  #数据库的配置
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost:///shopp_product?useUnicode=true&characterEncoding=UTF-8  #防止中文乱码
    url: jdbc:mysql:///shopp_product?useUnicode=true&characterEncoding=UTF-8  #防止中文乱码
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:com/moyu/shopp/mapper/*.xml #扫mapper映射
  type-aliases-package: com.moyu.shopp.domain,com.moyu.shopp.query  #别名的配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true